### ISSUE TITLE
Can't login 

### ISSUE THREAD

**Issue by a2910114** [samczsun/Skype4J#54]
Hello,
When I try to run next code I get error:

Windows 7, jdk1.8_45, skype version: 7.16.0.102

``` java
Skype skype = new SkypeBuilder(username, password).withAllResources().build();
skype.login();
skype.getEventDispatcher().registerListener(new Listener() {
  @EventHandler
  public void onMessage(MessageReceivedEvent e) {
    System.out.println("Got message: " + e.getMessage().getContent());
  }
});
skype.subscribe();
// Do stuff
skype.logout();
```

com.samczsun.skype4j.exceptions.ConnectionException: While fetching the asmtoken
    at com.samczsun.skype4j.internal.SkypeImpl.getAsmToken(SkypeImpl.java:364)
    at com.samczsun.skype4j.internal.client.FullClient.login(FullClient.java:251)
    at com.samczsun.skype4j.internal.client.FullClient.login(FullClient.java:234)
    at com.mykhaylenko.dellaparser.DellaPageTest.testSkype(DellaPageTest.java:85)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=204, URL=https://api.asm.skype.com/v1/skypetokenauth
    at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:435)
    at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:410)
    at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:164)
    at com.samczsun.skype4j.internal.SkypeImpl.getAsmToken(SkypeImpl.java:362)
    ... 29 more

**Comment by samczsun** [comment]
Jsoup has come to bite me in the rear one final time :(

**Comment by samczsun** [comment]
Fixed

**Comment by a2910114** [comment]
Thanks for quick response. Did you update maven dependency? I got the same error, I suppose that jar file on maven is still the same. Jar downloaded from Jenkins works as apropriate. 

Thanks a lot.
